version: '3'
services:
  api:
    build:
      context: .
    image: 'prodtrak'
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    image: 'mongo:latest'
    container_name: mongo
    ports:
      - "27017:27017"