version: '3'
services:
  api:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    network_mode: "host"
  mongo:
    image: 'mongo:latest'
    ports:
      - "27017:27017"